# Generated by Django 3.2.6 on 2024-10-24 15:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feedbackstudent',
            name='student',
        ),
        migrations.RemoveField(
            model_name='leavereportstaff',
            name='staff',
        ),
        migrations.RemoveField(
            model_name='leavereportstudent',
            name='student',
        ),
        migrations.RemoveField(
            model_name='notificationstaff',
            name='staff',
        ),
        migrations.RemoveField(
            model_name='notificationstudent',
            name='student',
        ),
        migrations.DeleteModel(
            name='FeedbackStaff',
        ),
        migrations.DeleteModel(
            name='FeedbackStudent',
        ),
        migrations.DeleteModel(
            name='LeaveReportStaff',
        ),
        migrations.DeleteModel(
            name='LeaveReportStudent',
        ),
        migrations.DeleteModel(
            name='NotificationStaff',
        ),
        migrations.DeleteModel(
            name='NotificationStudent',
        ),
    ]
